// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvirfhoshhotjmenxidf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2aXJmaG9zaGhvdGptZW54aWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjM4NDIsImV4cCI6MjA2OTk5OTg0Mn0.tOLBo5_bqT8UnpSQyb2FY_Ws5lKo2Ng0P-FZft2hz4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});